core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('legalysis.urls', namespace='legalysis'))
]

core/legalysis/urls.py
from django.urls import path
from django.views.generic import TemplateView
from legalysis import views


app_name = 'legalysis'
urlpatterns = [
    path('', views.UploadDocument.as_view(), name='homepage'),
    path('chat/', views.Chat.as_view(), name='chat'),
    path('uploaded-documents/',TemplateView.as_view(template_name="legalysis/test.html"), name="uploaded_documents")
]

core/legalysis/models.py
from django.contrib.auth.models import User
from django.db import models


class Document(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    document = models.FileField(upload_to='documents')
    

core/legalysis/forms.py
from django import forms

class FileForm(forms.Form):
    document = forms.FileField(label='Upload your documents', required=True)
    

core/legalysis/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import FormView
from legalysis.forms import FileForm
from legalysis.models import Document, User


# class UploadDocument(View):
    
#     def get(self, request):
#         form = FileForm()
#         return render(request, 'legalysis/index.html', {'form': form})
    
    
#     def post(self, request):
#         form = FileForm(request.POST, request.FILES)
#         if form.is_valid():
#             doc = form.cleaned_data['document']
#             document = Document(user=User.objects.get(username='admin'), document=doc)
#             document.save()
#             return render(request, 'legalysis
# /index.html', {'form': form})
            
#         else:
#             return render(request, 'legalysis/index.html', {'form': form})
        
        
class UploadDocument(FormView):
    template_name = 'legalysis/index.html'
    form_class = FileForm
    success_url = "/chat/"
    model = Document
    
    def form_valid(self, form):
        doc = form.cleaned_data['document']
        document = Document(user=User.objects.get(username='admin'), document=doc)
        document.save()
        return super().form_valid(form)
    

class Chat(View):
    def get(self, request):
        return render(request, 'legalysis/chat.html')
    
    def post(self, request):
        prompt = request.POST['prompt']
        return render(request, 'legalysis/chat.html')
        

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block title %}
        <title>Legalysis</title>
    {% endblock %}
</head>
<body>
    <div class="main-container">
    <section class="main-page-left">
        <div class="logo-title">
            <img src="{% static 'images/logo.png' %}" alt="">
            <h3> <a href="{% url 'legalysis:homepage' %}">Legalysis</a></h3>
        </div>
        <div class="menu">
            <div class="menu-item">
                <img class="menu-img" src="{% static 'images/chat.png' %}" alt="">
                <h3> <a href="{% url 'legalysis:chat' %}">Chats</a></h3>

            </div>
            <hr>
            <!-- <div class="menu-item">
                <img class="menu-img"src="{% static 'images/search.png' %}" alt="">
                <h3>Search</h3>
            </div>
            <hr> -->

            <div class="menu-item">
                <img class="menu-img"src="{% static 'images/folder.png' %}" alt="">
                <h3> <a href="{% url 'legalysis:uploaded_documents' %}">Saved Documents</a></h3>
            </div>
            <hr>
            <!-- <div class="menu-item">
                <img class="menu-img"src="{% static 'images/setting.png' %}" alt="">
                <h3>Setting</h3>
            </div>
            <hr> -->

        </div>
    </section>

    {% block main-page-right %}
        <section class="main-page-right">

        </section>
    {% endblock %}
</div>
</body>
</html>

core/templates/legalysis/chat.html
{% extends 'base.html' %}
{% load static %}
{% block main-page-right %}
<section class="main-page-right" id="chat-id">

    <div class="chat-setting">
        <div class="previous-chat top">
            <p class="user">Here, is question chat</p>
            <p class="robot">This is answer </p>
            <p class="user">Here, is question chat</p>
            <p class="robot">This is answer </p>
            <p class="user">Here, is question chat</p>
            <p class="robot">This is answer </p>
        </div>
        <form action="" method="POST" class="chatbox bottom">
            {% csrf_token %}
            <label for="prompt" id="prompt"></label>
            <textarea class="prompt" name="prompt" placeholder="Ask your Query"></textarea>
            <button class="btn" type="submit">Ask</button>
        </form>
    </div>

</section>
    {% endblock %}

core/templates/legalysis/index.html
{% extends 'base.html' %}
{% load static %}
{% block main-page-right %}
<section class="main-page-right">

        <div class="features-grid">
            <div class="feature-items">
                <img src="{% static 'images/features/pdf.png' %}" alt="">
                <p>Verify If your document is Non-Disclosure Document</p>
            </div>
            <div class="feature-items">
                <img src="{% static 'images/features/clauses.png' %}" alt="">
                <p>Extract main clauses</p>
            </div>
            <div class="feature-items">
                <img src="{% static 'images/features/summary.png' %}" alt="">
                <p>Get document summary</p>
            </div>
            <div class="feature-items">
                <img src="{% static 'images/features/entity.png' %}" alt="">
                <p>Identify main entities</p>
            </div>

            <div class="document-input feature-items">
                <form action="" method="POST"  enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <div>
                        {{ form }}
                    </div>
                    <button class="btn" type="submit">Upload</button>
             </form>
            </div>
        </div>
        </section>  
{% endblock %}

core/templates/legalysis/test.html
{% extends 'base.html' %}